### ISSUE TITLE
add REST endpoint to retrieve proposals vote

### ISSUE THREAD

**Issue by aleem1314** [vitwit/authz-apps#28]
# Summary

- [x] Add a new REST endpoint `/votes/{chainName}`, which accepts `start` and `end` dates, and returns all the validator votes from the `logs` table for a specific chain name.
- [x] Add a new REST endpoint `/votes`, which also accepts `start` and `end` dates, and returns all the validator votes from the `logs` table for all chains, without specifying a chain name.

Both endpoints should return a JSON response structured like this:

```
{
  "osmosis":[
    {
      "proposalID":"123",
      "title":"proposal title-2",
      "vote_option": "yes",
    },
    {
      "proposalID":"123",
      "title":"proposal title-2",
      "vote_option": "yes",
    }
  ],
 "regen":[
    {
      "proposalID":"123",
      "title":"proposal title-2",
      "vote_option": "yes",
    },
    {
      "proposalID":"123",
      "title":"proposal title-2",
      "vote_option": "yes",
    }
  ]
}
```

**Comment by deepan95dev** [comment]
Raised PR #35  @aleem1314

**Comment by deepan95dev** [comment]
I have taken values from request query for 'chainName' as well. Will that work or shall I modify to take chain Name from URL param?

Currently URL looks like `?chainName=osmosis&start=1700134476&end=1700134650`
